# please set the config parameters

# details of the data files
datafiles:
# Excel files in agreed format
  - name: "Master_Dataset_KB-Google.xlsx"
    location: "data/"
    start_date: 2017, 02, 09                # format: year,month,date
    end_date: 2020, 03, 17
  - name: "Google_KB_Test_Dataset.xlsx"
    location: "data/"
    start_date: 2020, 05, 01
    end_date: 2020, 08, 20
# csv file with the sub center ids, where the camps will be held in the next prediction window
# this file is needed to filter out only the needed ANMs, so that it will be easier to rank them
next_sub_center_ids_file: "data/next_sub_center_ids.csv"
# dates to be ignored. Keep blank if no dates should be ignored
# if multiple date ranges are to be ignored, add them likewise
ignore_dates:
    - start_date: 2020, 03, 18
      end_date: 2020, 04, 30
